name: Build Erlang Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Erlang Project
        uses: 4211421036/ErlangBuilder@v1.0.2
        with:
          erlang-source: './pm.erl'  # Path ke file atau direktori Erlang Anda punya
          build-mode: 'build'     # 'build' untuk executable, 'debug' untuk debugging
          output-dir: './build'   # Direktori output (akan dibuat otomatis)
          erts-version: '25.0'    # Versi Erlang/OTP (opsional)
